### ISSUE TITLE
Add example folder with an isolated working example

### ISSUE THREAD

**Issue by martensms** [maurizzzio/PojoViz#5]
Hey,

the documentation is pretty much unclear on how to use the project.

How to make a simple example? I mean, like having an example folder, containing a simple index.html, pojoviz.all.js and jquery.min.js (which gets analyzed as an example).

Currently my installation has 11,4MB of dependencies - and no demo where I can play around with what is happening. Is this the intension of the library?

**Comment by soundyogi** [comment]
I think this is awesome, but i have to second that - A little getting started guide would be much appreciated

**Comment by maurizzzio** [comment]
Hi, thanks for letting me know about this issue, as of now I'm not working actively on this project but luckily this weekend will be 4 days long in Bolivia :), I'll update the inner structure of the library with the knowledge I have acquired over the months and also make a playground (which will be useful to explain the inner workings of the library), stay tuned...

**Comment by maurizzzio** [comment]
hey took me a little bit but I think http://maurizzzio.github.io/PojoViz/public/vulcanize.html#development now has a solid getting started guide, I hope you like it

**Comment by soundyogi** [comment]
Great! Thanks Man! :)
